name: Acme-Hooli Integration CI

on:
  push:
    branches:
      - main

jobs:
  # Build and publish Acme CRM component
  acme_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            acme_component:
              - 'components/acme-crm/**'
      - uses: actions/setup-node@v4.0.2
        if: steps.filter.outputs.acme_component == 'true'
      - name: Install dependencies
        run: yarn install
        if: steps.filter.outputs.acme_component == 'true'
      - name: Build Acme CRM Component
        run: yarn build
        working-directory: components/acme-crm
        if: steps.filter.outputs.acme_component == 'true'
      - name: Publish Acme CRM Component
        uses: .github/actions/component-publisher
        with:
          COMPONENT_PATH: components/acme-crm
          PRISMATIC_URL: ${{ vars.PRISMATIC_URL }}
          PRISM_REFRESH_TOKEN: ${{ secrets.PRISM_REFRESH_TOKEN }}
          COMMENT: This is a test comment
        if: steps.filter.outputs.acme_component == 'true'
      - name: Note that component didn't change
        run: |
          echo "No changes detected for Acme component" >> "$GITHUB_STEP_SUMMARY"
        if: steps.filter.outputs.acme_component != 'true'

  # Build and publish Hooli CRM component
  hooli_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            hooli_component:
              - 'components/hooli-crm/**'
      - uses: actions/setup-node@v4.0.2
        if: steps.filter.outputs.hooli_component == 'true'
      - name: Install dependencies
        run: yarn install
        if: steps.filter.outputs.hooli_component == 'true'
      - name: Build Hooli CRM Component
        run: yarn build
        working-directory: components/hooli-crm
        if: steps.filter.outputs.hooli_component == 'true'
      - name: Publish Hooli CRM Component
        uses: prismatic-io/component-publisher@v1.1
        with:
          COMPONENT_PATH: components/hooli-crm
          PRISMATIC_URL: ${{ vars.PRISMATIC_URL }}
          PRISM_REFRESH_TOKEN: ${{ secrets.PRISM_REFRESH_TOKEN }}
        if: steps.filter.outputs.hooli_component == 'true'
      - name: Note that component didn't change
        run: |
          echo "No changes detected for Hooli component" >> "$GITHUB_STEP_SUMMARY"
        if: steps.filter.outputs.hooli_component != 'true'

  # Publish Acme-Hooli integration after components are published
  acme_hooli_integration:
    runs-on: ubuntu-latest
    needs: [acme_component, hooli_component]
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            integration_or_components:
              - 'integrations/hooli-acme-integration.yml'
              - 'components/**'
      - name: Publish Integration Component
        uses: prismatic-io/integration-publisher@v1.1
        with:
          PATH_TO_YML: integrations/hooli-acme-integration.yml
          PRISMATIC_URL: ${{ vars.PRISMATIC_URL }}
          PRISM_REFRESH_TOKEN: ${{ secrets.PRISM_REFRESH_TOKEN }}
          INTEGRATION_ID: ${{ vars.ACME_HOOLI_INTEGRATION_ID_US_PROD}}
          MAKE_AVAILABLE_IN_MARKETPLACE: false
        if: steps.filter.outputs.integration_or_components == 'true'
      - name: Note that integration didn't change
        run: |
          echo "No changes detected for integration or underlying components" >> "$GITHUB_STEP_SUMMARY"
        if: steps.filter.outputs.integration_or_components != 'true'
